name: Android Release Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter --version # Diagnostic

      - name: Get dependencies
        run: flutter pub get

      # Added Analysis and Tests
      - name: Analyze project
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Start release build (APKs)
        run: flutter build apk --split-per-abi --target-platform android-arm,android-arm64 --release

      - name: Upload release APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apks
          path: build/app/outputs/apk/release/
          # retention-days: 5 # Optional: if you want to limit artifact retention